services:
  service-app:
    build: ./services/app
    ports:
      - "4002:4002"
    environment:
      - DATABASE_URL=${POSTGRE_DB_URL}
  service-users:
    build: ./services/users
    ports:
      - "4001:4001"
    environment:
      - DATABASE_URL=${MONGO_DB_URL}
  orchestrator:
    build: ./orchestrator-graphql
    ports:
      - "3005:4000"
    environment:
      - POSTS_SERVICE_URL=http://service-app:4002
      - USER_SERVICE_URL=http://service-users:4001