version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: P3-C1
    ports:
      - "6662:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://root:root@postgres:5432/P3-C1-PROD
    depends_on:
      - postgres
  client-user:
    build: ./client-user
    ports:
      - "5173:80"
  client-admin:
    build: ./client-admin
    ports:
      - "5174:80"
volumes:
  postgres_data:
